export const SECRET_PLACEHOLDER_PREFIX = '[[TAVIRAQ_SECRET_'
export const SECRET_PLACEHOLDER_PATTERN = String.raw`\[\[TAVIRAQ_SECRET_\d+_[A-Z0-9_]+\]\]`
export const SECRET_PLACEHOLDER_RE = new RegExp(SECRET_PLACEHOLDER_PATTERN)
export const SECRET_PLACEHOLDER_GLOBAL_RE = new RegExp(SECRET_PLACEHOLDER_PATTERN, 'g')
export const DISPLAY_SECRET_LABEL = '[secret]'
